### ISSUE TITLE
Add unarchived and archived scope support

### ISSUE THREAD

**Issue by bravely** [johnotander/archivable#7]
```
[1] pry(main)> ProductDefinition.unarchived
NoMethodError: undefined method `scoped' for #<Class:0x007ffda6a9f438>
```

**Comment by johno** [comment]
Archivable doesn't currently support scopes, they need to be manually added to your model. However, I'm hoping to support that feature in the next version.

**Comment by bravely** [comment]
Yeah, I was mostly making this so I'd put the time in to add it later.

**Comment by johno** [comment]
:+1: :sunglasses:
